version: "2"
services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
  client:
    build: ../fonio/
    restart: unless-stopped
    volumes_from:
      - api
    links:
      - api
    ports:
      - "3000:3000"